apiVersion: v1
kind: Service
metadata:
  name: jss-xray-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
  {{- end }}
  selector: {app: jss-xray-frontend}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jss-xray-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {app: jss-xray-frontend}
  template:
    metadata:
      labels: {app: jss-xray-frontend}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_INTERNAL_URL
              value: "http://jss-xray-backend:8000"
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
